import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Search,MapPin,Navigation,RefreshCw,Heart,Settings,Sun,CloudSun,Cloud,Rainy,CloudLightning,Snowflake,CloudFog,Wind,Eye,Droplets,Sunrise,Sunset,Compass,AlertTriangle,Map as MapIcon,Clock,ChevronRight,LocateFixed}from'lucide-react';import{LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid}from'recharts';import'leaflet/dist/leaflet.css';import'./styles/app.css';
const API=import.meta.env.VITE_API_BASE||'/api';
const codeMap={0:['Clear sky','sun'],1:['Mainly clear','sun'],2:['Partly cloudy','partly'],3:['Overcast','cloud'],45:['Fog','fog'],48:['Depositing rime fog','fog'],51:['Light drizzle','rain'],53:['Drizzle','rain'],55:['Heavy drizzle','rain'],61:['Light rain','rain'],63:['Rain','rain'],65:['Heavy rain','rain'],71:['Light snow','snow'],73:['Snow','snow'],75:['Heavy snow','snow'],80:['Rain showers','rain'],81:['Rain showers','rain'],82:['Heavy rain showers','rain'],85:['Snow showers','snow'],86:['Heavy snow showers','snow'],95:['Thunderstorm','storm'],96:['Thunderstorm with hail','storm'],99:['Severe thunderstorm','storm']};
function condition(code){return codeMap[code]||['Unknown','cloud']}
function Icon({kind,size=26}){const p={size,strokeWidth:1.7};return kind==='sun'?<Sun {...p}/>:kind==='partly'?<CloudSun {...p}/>:kind==='rain'?<Rainy {...p}/>:kind==='storm'?<CloudLightning {...p}/>:kind==='snow'?<Snowflake {...p}/>:kind==='fog'?<CloudFog {...p}/>:<Cloud {...p}/>}
const fmtTime=s=>new Date(s).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});const dayName=s=>new Date(s).toLocaleDateString([], {weekday:'short'});
function App(){const [place,setPlace]=useState({name:'Lala Musa',admin1:'Punjab',country:'Pakistan',latitude:32.702,longitude:73.957});const [data,setData]=useState(null);const [q,setQ]=useState('');const [results,setResults]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('ww-saved')||'[]'));const [unit,setUnit]=useState(()=>localStorage.getItem('ww-unit')||'C');const [tab,setTab]=useState('Home');const [favoritesOpen,setFavoritesOpen]=useState(false);const [settingsOpen,setSettingsOpen]=useState(false);
useEffect(()=>{let t; if(q.trim().length<2){setResults([]);return} t=setTimeout(async()=>{try{const r=await fetch(`${API}/api/geocode?q=${encodeURIComponent(q)}`);setResults(await r.json())}catch{setResults([])}},280);return()=>clearTimeout(t)},[q]);
const load=async(p=place)=>{setLoading(true);setError('');try{const r=await fetch(`${API}/api/weather?lat=${p.latitude}&lon=${p.longitude}`);if(!r.ok)throw Error();setData(await r.json())}catch{setError('Unable to load weather right now.');}finally{setLoading(false)}};
useEffect(()=>{load(place)},[]);useEffect(()=>{localStorage.setItem('ww-saved',JSON.stringify(saved))},[saved]);
const current=data?.current;const [cond,kind]=condition(current?.weather_code);const c=v=>unit==='F'?Math.round(v*9/5+32):Math.round(v);const wind=v=>unit==='F'?Math.round(v*0.621371):Math.round(v);const hourly=useMemo(()=>{if(!data)return[];const now=new Date();let i=data.hourly.time.findIndex(x=>new Date(x)>=now);if(i<0)i=0;return data.hourly.time.slice(i,i+24).map((t,j)=>({time:t,temp:c(data.hourly.temperature_2m[i+j]),rain:data.hourly.precipitation_probability[i+j],code:data.hourly.weather_code[i+j],wind:data.hourly.wind_speed_10m[i+j]}))},[data,unit]);
const selectPlace=p=>{setPlace(p);setQ('');setResults([]);setFavoritesOpen(false);load(p)};const useLocation=()=>navigator.geolocation?.getCurrentPosition(async pos=>{const p={name:'Current location',admin1:'',country:'',latitude:pos.coords.latitude,longitude:pos.coords.longitude};try{const r=await fetch(`${API}/api/reverse?lat=${pos.coords.latitude}&lon=${pos.coords.longitude}`);const a=await r.json();if(a?.name)Object.assign(p,a);}catch{}selectPlace(p)},()=>setError('Location permission is unavailable. Search for a location manually.'));
const toggleSave=()=>setSaved(s=>s.some(x=>x.latitude===place.latitude&&x.longitude===place.longitude)?s.filter(x=>x.latitude!==place.latitude||x.longitude!==place.longitude):[...s,place]);
const theme=current?(current.is_day?'day':'night'):'night';
return <div className={`app ${theme} ${kind}`}><div className="atmosphere"/><header><div className="brand"><div className="brandMark"><Sun size={19}/></div><div><b>WORLD WEATHER</b><span>Weather, wherever you are.</span></div></div><div className="searchWrap"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, town or location…"/><button className="locBtn" onClick={useLocation} title="Use my location"><LocateFixed size={19}/></button>{results.length>0&&<div className="results">{results.map(r=><button key={r.id} onClick={()=>selectPlace(r)}><MapPin size={17}/><span><strong>{r.name}</strong><small>{[r.admin1,r.country].filter(Boolean).join(', ')}</small></span></button>)}</div>}</div><div className="headerActions"><button onClick={toggleSave} className={saved.some(x=>x.latitude===place.latitude&&x.longitude===place.longitude)?'active':''}><Heart size={19}/></button><button onClick={()=>setSettingsOpen(v=>!v)}><Settings size={19}/></button></div></header>
{settingsOpen&&<div className="settings"><b>Settings</b><label>Temperature <select value={unit} onChange={e=>{setUnit(e.target.value);localStorage.setItem('ww-unit',e.target.value)}}><option>C</option><option>F</option></select></label><button onClick={()=>setFavoritesOpen(true)}>Saved locations</button></div>}
{favoritesOpen&&<div className="modal"><div className="modalCard"><div className="modalHead"><b>My Locations</b><button onClick={()=>setFavoritesOpen(false)}>×</button></div>{saved.length===0?<p className="muted">No saved locations yet.</p>:saved.map(x=><button className="savedRow" key={x.id||x.name} onClick={()=>selectPlace(x)}><MapPin size={17}/><span>{x.name}<small>{[x.admin1,x.country].filter(Boolean).join(', ')}</small></span></button>)}</div></div>}
<main><nav className="tabs">{['Home','Hourly','10-Day','Map','Saved'].map(x=><button className={tab===x?'selected':''} onClick={()=>{setTab(x);if(x==='Saved')setFavoritesOpen(true)}} key={x}>{x==='Map'?<MapIcon size={17}/>:x==='Saved'?<Heart size={17}/>:null}{x}</button>)}</nav>{tab==='Map'&&data&&<section className="card mapCard"><SectionTitle title="Weather Map"/><div className="mapFrame"><iframe title="World Weather map" src={`https://www.openstreetmap.org/export/embed.html?bbox=${place.longitude-0.08}%2C${place.latitude-0.06}%2C${place.longitude+0.08}%2C${place.latitude+0.06}&layer=mapnik&marker=${place.latitude}%2C${place.longitude}`}/></div><p className="muted">Map centered on {place.name}. Weather layers can be added through a licensed tile provider.</p></section>}{error&&<div className="error"><AlertTriangle size={18}/>{error}<button onClick={()=>load()}>Try Again</button></div>}
{loading?<Skeleton/>:data&&<><section className="hero"><div className="heroTop"><div><div className="eyebrow"><MapPin size={15}/>{place.name}{place.country?`, ${place.country}`:''}</div><div className="updated"><Clock size={14}/> Updated recently</div></div><button className="refresh" onClick={()=>load()}><RefreshCw size={17}/></button></div><div className="heroMain"><div><div className="temp">{c(current.temperature_2m)}°</div><div className="feels">Feels like {c(current.apparent_temperature)}°</div><div className="condition"><Icon kind={kind} size={32}/><span>{cond}</span></div></div><div className="heroIcon"><Icon kind={kind} size={112}/></div></div><div className="heroStats"><Stat icon={<Droplets/>} label="Humidity" value={`${current.relative_humidity_2m}%`}/><Stat icon={<Wind/>} label="Wind" value={`${wind(current.wind_speed_10m)} ${unit==='F'?'mph':'km/h'}`}/><Stat icon={<Sun/>} label="UV" value={data.daily.uv_index_max[0]??'—'}/><Stat icon={<Eye/>} label="Visibility" value={`${Math.round((data.hourly.visibility.find((_,i)=>i>=0)||0)/1000)} km`}/></div></section>
<section><SectionTitle title="Hourly Forecast"/><div className="hourly">{hourly.map((h,i)=><div className={`hour ${i===0?'now':''}`} key={h.time}><b>{i===0?'NOW':fmtTime(h.time)}</b><Icon kind={condition(h.code)[1]} size={25}/><strong>{h.temp}°</strong><small>{h.rain}% rain</small></div>)}</div></section>
<section className="grid2"><div className="card chartCard"><SectionTitle title="Temperature" action="Next 24 hours"/><div className="chart"><ResponsiveContainer width="100%" height={230}><LineChart data={hourly}><CartesianGrid vertical={false} strokeDasharray="3 5" opacity={.15}/><XAxis dataKey="time" tickFormatter={v=>new Date(v).toLocaleTimeString([], {hour:'numeric'})} minTickGap={28}/><YAxis hide domain={['dataMin-2','dataMax+2']}/><Tooltip labelFormatter={v=>fmtTime(v)} formatter={v=>[`${v}°`,'Temperature']}/><Line type="monotone" dataKey="temp" stroke="currentColor" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></div><div className="card rainCard"><SectionTitle title="Rain forecast"/><div className="bigStat">{data.daily.precipitation_probability_max[0]??0}<span>%</span></div><p>Chance of precipitation today</p><div className="rainBars">{hourly.slice(0,12).map(h=><div key={h.time} style={{height:`${Math.max(5,h.rain)}%`}} title={`${h.rain}%`}/>)}</div><small>Hourly precipitation probability</small></div></section>
<section><SectionTitle title="10-Day Forecast"/><div className="days">{data.daily.time.map((t,i)=><div className="day" key={t}><span><b>{i===0?'Today':dayName(t)}</b><small>{new Date(t).toLocaleDateString([], {month:'short',day:'numeric'})}</small></span><Icon kind={condition(data.daily.weather_code[i])[1]} size={25}/><small>{data.daily.precipitation_probability_max[i]??0}%</small><strong>{c(data.daily.temperature_2m_max[i])}° <em>{c(data.daily.temperature_2m_min[i])}°</em></strong></div>)}</div></section>
<section className="grid3"><InfoCard title="Wind" icon={<Compass/>}><div className="windDial"><Compass size={70} style={{transform:`rotate(${current.wind_direction_10m}deg)`}}/><b>{wind(current.wind_speed_10m)} {unit==='F'?'mph':'km/h'}</b></div><p>{dir(current.wind_direction_10m)} · Gusts {wind(current.wind_gusts_10m)} {unit==='F'?'mph':'km/h'}</p></InfoCard><InfoCard title="Humidity & UV" icon={<Droplets/>}><div className="metricLine"><span>Humidity</span><b>{current.relative_humidity_2m}%</b></div><div className="metricLine"><span>UV Index</span><b>{data.daily.uv_index_max[0]??'—'}</b></div><div className="metricLine"><span>Dew point</span><b>{c(data.hourly.dew_point_2m[0])}°</b></div></InfoCard><InfoCard title="Sunrise & Sunset" icon={<Sunrise/>}><div className="sunTrack"><span>Sunrise<br/><b>{fmtTime(data.daily.sunrise[0])}</b></span><div><i/></div><span>Sunset<br/><b>{fmtTime(data.daily.sunset[0])}</b></span></div><p className="muted">Sun position adapts to local time.</p></InfoCard></section>
<div className="source">Live weather data · Forecast is a prediction, not a guarantee · Provider: Open-Meteo</div></>}</main><footer><span>WORLD WEATHER</span><span>Live weather data</span><span>Weather, wherever you are.</span></footer></div>}
function dir(d){return ['N','NE','E','SE','S','SW','W','NW'][Math.round(d/45)%8]}
function Stat({icon,label,value}){return <div className="stat">{icon}<span>{label}</span><b>{value}</b></div>}
function SectionTitle({title,action}){return <div className="sectionTitle"><h2>{title}</h2>{action&&<small>{action}</small>}</div>}
function InfoCard({title,icon,children}){return <div className="card info"><SectionTitle title={title}/>{children}</div>}
function Skeleton(){return <div className="skeletons"><div className="sk heroSk"/><div className="sk"/><div className="sk"/></div>}
createRoot(document.getElementById('root')).render(<App/>);

if ('serviceWorker' in navigator) { window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js').catch(() => {})); }
