import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import morgan from 'morgan';
import {LRUCache} from 'lru-cache';
const app=express(); const PORT=process.env.PORT||8787;
app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:process.env.CLIENT_ORIGIN||true})); app.use(compression()); app.use(express.json()); app.use(morgan('tiny'));
const cache=new LRUCache({max:500,ttl:5*60*1000});
const json=async(url,opts={})=>{const r=await fetch(url,opts); if(!r.ok) throw new Error(`Upstream ${r.status}`); return r.json()};
app.get('/api/geocode',async(req,res)=>{try{const q=String(req.query.q||'').trim(); if(q.length<2)return res.json([]); if(/^[-+]?\d+(?:\.\d+)?\s*,\s*[-+]?\d+(?:\.\d+)?$/.test(q)){const [latitude,longitude]=q.split(',').map(Number);return res.json([{id:`${latitude},${longitude}`,name:'Coordinates',admin1:'',country:'',countryCode:'',latitude,longitude,timezone:'auto'}]);} const key=`geo:${q.toLowerCase()}`; const hit=cache.get(key); if(hit)return res.json(hit); const u=new URL('https://geocoding-api.open-meteo.com/v1/search'); u.searchParams.set('name',q);u.searchParams.set('count','8');u.searchParams.set('language','en');u.searchParams.set('format','json'); const d=await json(u); const out=(d.results||[]).map(x=>({id:`${x.latitude},${x.longitude}`,name:x.name,admin1:x.admin1||'',country:x.country||'',countryCode:x.country_code||'',latitude:x.latitude,longitude:x.longitude,timezone:x.timezone||''})); cache.set(key,out); res.json(out);}catch(e){res.status(502).json({error:'Geocoding unavailable'});}});

app.get('/api/reverse',async(req,res)=>{try{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'Invalid coordinates'});const key=`rev:${lat.toFixed(4)},${lon.toFixed(4)}`;const hit=cache.get(key);if(hit)return res.json(hit);const u=new URL('https://geocoding-api.open-meteo.com/v1/reverse');u.searchParams.set('latitude',lat);u.searchParams.set('longitude',lon);u.searchParams.set('language','en');u.searchParams.set('format','json');const d=await json(u);const x=(d.results||[])[0];const out=x?{id:`${x.latitude},${x.longitude}`,name:x.name||'Current location',admin1:x.admin1||'',country:x.country||'',countryCode:x.country_code||'',latitude:x.latitude,longitude:x.longitude,timezone:x.timezone||''}:{name:'Current location',admin1:'',country:'',latitude:lat,longitude:lon};cache.set(key,out);res.json(out);}catch(e){res.status(502).json({error:'Reverse geocoding unavailable'});}});
app.get('/api/weather',async(req,res)=>{try{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)return res.status(400).json({error:'Invalid coordinates'}); const key=`weather:${lat.toFixed(4)},${lon.toFixed(4)}`;const hit=cache.get(key);if(hit)return res.json(hit); const u=new URL('https://api.open-meteo.com/v1/forecast'); u.searchParams.set('latitude',lat);u.searchParams.set('longitude',lon);u.searchParams.set('timezone','auto');u.searchParams.set('forecast_days','10');u.searchParams.set('current','temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,rain,weather_code,cloud_cover,pressure_msl,wind_speed_10m,wind_direction_10m,wind_gusts_10m');u.searchParams.set('hourly','temperature_2m,apparent_temperature,precipitation_probability,precipitation,rain,weather_code,relative_humidity_2m,cloud_cover,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,uv_index,dew_point_2m');u.searchParams.set('daily','weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_probability_max,precipitation_sum,rain_sum,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,sunrise,sunset,uv_index_max'); const d=await json(u); cache.set(key,d);res.json(d);}catch(e){res.status(502).json({error:'Weather provider unavailable'});}});
app.get('/api/health',(req,res)=>res.json({ok:true,provider:'Open-Meteo'}));
app.listen(PORT,()=>console.log(`World Weather API listening on ${PORT}`));
